# Generated by Django 4.1.2 on 2022-10-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_peaple'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peaple',
            new_name='People',
        ),
    ]
